TITLE 41056P NEW LISTENER

REM Log File Name
set ACTIVITY_LOG="activity_41056P"

REM The listener watches this directory for batch files
set WATCH_DIR_41056P="C:\41056P"

REM Processed batches are moved to this folder
set PROCESSED_41056P="C:\processed_41056P"

REM Delay between successive batches
set DELAY_BETWEEN_ITERATION_41056P=120

REM Hotfolder Directory
set HOT_FOLDER=c:\41056H

REM folder.cfg directory
set CONFIG_FOLDER=C:\41056H\[_EFI_HotFolder_]

REM NAME OF THE LISTENER
set PRINTER_NAME="41056_PRINTER_LISTENER"

REM TYPE OF WRAPS BEING PRINTED  AT ANY GIVEN POINT OF TIME
set HOTFOLDER_FILE_EXTENSION_PATTERN="*.*"

REM TYPE OF BATCHES BEING SENT BY MEDIALYNX
set BATCH_FILE_EXTENSION="*.txt"

REM NUMBER OF ITERATIONS THE LISTENER WILL DO LOOKING FOR FILES IN HOTFOLDER DIRECTORY
set HOT_FOLDER_CHK_CNT=2

REM NUMBER OF SECONDS (PER ITERATION) WAIT BEFORE SENDING FILES TO HOTFOLDER ...IN THIS INSTANCE ITS 30*2 = 60 SECONDS
set HOTFOLDER_WAIT_SECONDS=30 
 

c:\java13\bin\java -Dactivity_log=%ACTIVITY_LOG% -cp .;C:/41056P_new_printer_listener;C:/41056P_new_printer_listener/41056P_new_printer_listener.jar; com.directory.DirectoryWatcher %WATCH_DIR_41056P% %PROCESSED_41056P% %DELAY_BETWEEN_ITERATION_41056P%  %HOT_FOLDER% %CONFIG_FOLDER% %HOT_FOLDER_CHK_CNT%  %PRINTER_NAME% %HOTFOLDER_FILE_EXTENSION_PATTERN% %HOTFOLDER_WAIT_SECONDS% %BATCH_FILE_EXTENSION%
pause